package interfaces;
import java.util.List;
import java.util.concurrent.Callable;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import framework.AssertKeyword;

public interface IAssert extends Callable<Void> {
	AssertKeyword assertText(By locator, String expected, long timeoutSeconds);
	AssertKeyword assertText(WebElement element, String expected, long timeoutSeconds);
	AssertKeyword assertTextContains(By locator, String expected, long timeoutSeconds);
	AssertKeyword assertTextContains(WebElement element, String expected, long timeoutSeconds);
	AssertKeyword assertValue(By locator, String expected, long timeoutSeconds);
	AssertKeyword assertValue(WebElement element, String expected, long timeoutSeconds);
	AssertKeyword assertValueContains(By locator, String expected, long timeoutSeconds);
	AssertKeyword assertValueContains(WebElement element, String expected, long timeoutSeconds);
	AssertKeyword assertElementAttributeValue(By locator, String attrName, String expected, long timeoutSeconds);
	AssertKeyword assertElementAttributeValue(WebElement element, String attrName, String expected, long timeoutSeconds);
	AssertKeyword assertElementAttributeValueContains(By locator, String attrName, String expected, long timeoutSeconds);
	AssertKeyword assertElementAttributeValueContains(WebElement element, String attrName, String expected, long timeoutSeconds);
	AssertKeyword assertElementExists(By locator, long timeoutSeconds);
	AssertKeyword assertElementVisible(By locator, long timeoutSeconds);
	AssertKeyword assertElementVisible(WebElement element, long timeoutSeconds);
	AssertKeyword assertElementNotVisible(By locator, long timeoutSeconds);
	AssertKeyword assertElementNotVisible(WebElement element, long timeoutSeconds);
	AssertKeyword assertElementEnabled(By locator, long timeoutSeconds);
	AssertKeyword assertElementEnabled(WebElement element, long timeoutSeconds);
	AssertKeyword assertElementNotEnabled(By locator, long timeoutSeconds);
	AssertKeyword assertElementNotEnabled(WebElement element, long timeoutSeconds);
	AssertKeyword assertElementSelected(By locator, long timeoutSeconds);
	AssertKeyword assertElementSelected(WebElement element, long timeoutSeconds);
	AssertKeyword assertElementNotSelected(By locator, long timeoutSeconds);
	AssertKeyword assertElementNotSelected(WebElement element, long timeoutSeconds);
	AssertKeyword assertPageTitleEquals(String title, long timeoutSeconds);
	AssertKeyword assertPageTitleContains(String title, long timeoutSeconds);
	AssertKeyword assertCurrentUrlEquals(String Url, long timeoutSeconds);
	AssertKeyword assertCurrentUrlContains(String Url, long timeoutSeconds);
	AssertKeyword assertAlertIsPresent(long timeoutSeconds);
	AssertKeyword assertLocatorReturnsNumberOfElements(By locator, int expectedNumber, long timeoutSeconds);
	AssertKeyword assertLocatorReturnsLessThan(By locator, int lessNumber, long timeoutSeconds);
	AssertKeyword assertLocatorReturnsGreaterThan(By locator, int greaterNumber, long timeoutSeconds);
	AssertKeyword assertDropDownSelectedTextIs(By locator, String name, long timeoutSeconds);
	AssertKeyword assertDropDownSelectedTextIs(WebElement element, String name, long timeoutSeconds);
	AssertKeyword assertDropDownSelectedValueIs(By locator, String name, long timeoutSeconds);
	AssertKeyword assertDropDownSelectedValueIs(WebElement element, String name, long timeoutSeconds);
	AssertKeyword assertDropDownItemCountIs(By locator, int count, long timeoutSeconds);
	AssertKeyword assertDropDownItemCountIs(WebElement element, int count, long timeoutSeconds);
	AssertKeyword assertDropDownCountainsOption(By locator, String text, long timeoutSeconds);
	AssertKeyword assertDropDownCountainsOption(WebElement element, String text, long timeoutSeconds);
	AssertKeyword assertDropDownCountainsOptions(By locator, List<String> text, long timeoutSeconds);
	AssertKeyword assertDropDownCountainsOptions(WebElement element, List<String> text, long timeoutSeconds);
	AssertKeyword assertDropDownOptionsInOrderOf(By locator, List<String> text, long timeoutSeconds);
	AssertKeyword assertDropDownOptionsInOrderOf(WebElement element, List<String> text, long timeoutSeconds);
	AssertKeyword assertText(By locator, String expected);
	AssertKeyword assertText(WebElement element, String expected);
	AssertKeyword assertTextContains(By locator, String expected);
	AssertKeyword assertTextContains(WebElement element, String expected);
	AssertKeyword assertValue(By locator, String expected);
	AssertKeyword assertValue(WebElement element, String expected);
	AssertKeyword assertValueContains(By locator, String expected);
	AssertKeyword assertValueContains(WebElement element, String expected);
	AssertKeyword assertElementAttributeValue(By locator, String attrName, String expected);
	AssertKeyword assertElementAttributeValue(WebElement element, String attrName, String expected);
	AssertKeyword assertElementAttributeValueContains(By locator, String attrName, String expected);
	AssertKeyword assertElementAttributeValueContains(WebElement element, String attrName, String expected);
	AssertKeyword assertElementExists(By locator);
	AssertKeyword assertElementVisible(By locator);
	AssertKeyword assertElementVisible(WebElement element);
	AssertKeyword assertElementNotVisible(By locator);
	AssertKeyword assertElementNotVisible(WebElement element);
	AssertKeyword assertElementEnabled(By locator);
	AssertKeyword assertElementEnabled(WebElement element);
	AssertKeyword assertElementNotEnabled(By locator);
	AssertKeyword assertElementNotEnabled(WebElement element);
	AssertKeyword assertElementSelected(By locator);
	AssertKeyword assertElementSelected(WebElement element);
	AssertKeyword assertElementNotSelected(By locator);
	AssertKeyword assertElementNotSelected(WebElement element);
	AssertKeyword assertPageTitleEquals(String title);
	AssertKeyword assertPageTitleContains(String title);
	AssertKeyword assertCurrentUrlEquals(String Url);
	AssertKeyword assertCurrentUrlContains(String Url);
	AssertKeyword assertAlertIsPresent();
	AssertKeyword assertLocatorReturnsNumberOfElements(By locator, int expectedNumber);
	AssertKeyword assertLocatorReturnsLessThan(By locator, int lessNumber);
	AssertKeyword assertLocatorReturnsGreaterThan(By locator, int greaterNumber);
	AssertKeyword assertDropDownSelectedTextIs(By locator, String name);
	AssertKeyword assertDropDownSelectedTextIs(WebElement element, String name);
	AssertKeyword assertDropDownSelectedValueIs(By locator, String name);
	AssertKeyword assertDropDownSelectedValueIs(WebElement element, String name);
	AssertKeyword assertDropDownItemCountIs(By locator, int count);
	AssertKeyword assertDropDownItemCountIs(WebElement element, int count);
	AssertKeyword assertDropDownCountainsOption(By locator, String text);
	AssertKeyword assertDropDownCountainsOption(WebElement element, String text);
	AssertKeyword assertDropDownCountainsOptions(By locator, List<String> text);
	AssertKeyword assertDropDownCountainsOptions(WebElement element, List<String> text);
	AssertKeyword assertDropDownOptionsInOrderOf(By locator, List<String> text);
	AssertKeyword assertDropDownOptionsInOrderOf(WebElement element, List<String> text);
}
